driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.6
    run_list: apt::default
  - name: freebsd-10.3
    run_list: freebsd::portsnap
  - name: freebsd-11.0
    run_list: freebsd::portsnap
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: macosx-10.11
    run_list: homebrew::default
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion

suites:
  - name: default
    run_list: openssh::default
  - name: iptables
    run_list: openssh::iptables
    excludes:
      - macosx-10.11
